name: Validate XML

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - "**/**.csl"
  push:
    branches:
      - main
    paths:
      - "**/**.csl"
  schedule:
    - cron: "0 3 * * 1"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: read

jobs:
  validate-xml:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Validate changed CSL styles
        if: github.event_name != 'schedule' && github.event_name != 'workflow_dispatch'
        uses: adunning/xml-model-validator@v2
        with:
          changed_files_only: true
          xml_model_rule_mode: fallback
          xml_model_rule_extension: csl
          xml_model_declarations: |
            href="https://raw.githubusercontent.com/citation-style-language/schema/refs/heads/master/schemas/styles/csl-repository.rnc" type="application/relax-ng-compact-syntax" schematypens="http://relaxng.org/ns/compatibility/annotations/1.0"
            href="https://raw.githubusercontent.com/citation-style-language/schema/refs/heads/master/schemas/styles/csl-repository.rnc" type="application/relax-ng-compact-syntax" schematypens="http://purl.oclc.org/dsdl/schematron"

      - name: Validate full CSL repository
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: adunning/xml-model-validator@v2
        with:
          xml_model_rule_mode: fallback
          xml_model_rule_extension: csl
          xml_model_declarations: |
            href="https://raw.githubusercontent.com/citation-style-language/schema/refs/heads/master/schemas/styles/csl-repository.rnc" type="application/relax-ng-compact-syntax" schematypens="http://relaxng.org/ns/compatibility/annotations/1.0"
            href="https://raw.githubusercontent.com/citation-style-language/schema/refs/heads/master/schemas/styles/csl-repository.rnc" type="application/relax-ng-compact-syntax" schematypens="http://purl.oclc.org/dsdl/schematron"
